Fix Docker CI
Sometimes the RedHat image fails with a
`../../src/cn-executable/rmap.c:28:44: error: initializer element is not constant`
so this commit tries to address that.

Sometimes the image build can't find alloc.h

`../../src/bennet/prelude.c:5:10: fatal error: bennet/state/alloc.h: No such file or directory`

but I think this is spurious.